### PR TITLE
Rename files/variables etc from MyProject/myproject etc

### PR DESCRIPTION
**Pull request by ddervs**
Hi Matt,

I'm on the MPHYG002 course and made this little script to make it easier to start new projects with your template by renaming all the instances of MyProject/myproject/the namespace etc.

Having run the renaming script, CMake builds without complaining on my machine (macOS Sierra,  AppleClang 8.0.0.8000042). I can't vouch for whether it would work on linux!

Cheers,
Danial

### CODE REVIEW

**Comment by MattClarkson** [comment]
Thanks for this. I'll take a look.

**Comment by MattClarkson** [comment]
Hi Danial,

Would you be happy to remove your copyright statement, and place the standard LICENSE info at the top of the rename.sh file?

If so, please can you provide a commit with this in?

Thanks

Matt

**Comment by ddervs** [comment]
Hi Matt,

Have pushed that to the rename branch, so feel free to merge it in.

Cheers,
Danial

On 28 Feb 2017, at 08:36, Matt Clarkson <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Danial,

Would you be happy to remove your copyright statement, and place the standard LICENSE info at the top of the rename.sh file?

If so, please can you provide a commit with this in?

Thanks

Matt

**Comment by MattClarkson** [comment]
Thanks for your contribution. This was manually merged, and manually updated.

**Pull request closed without merging**
